### ISSUE TITLE
[ILERI_JAVA_2018G] src/main/resources

### ISSUE THREAD

**Issue by cihangunacti** [ozkansari/MyCourses#1]
Hocam Merhaba 

src/main/resources altına resim css bootstrap koyup pathını veriyorum localhost'ta işlemiyor eclipse'te web browser ile başlatınca arkaplan oluyor 
bunun sebebi nedir acaba

Teşekkurler

**Comment by ozkansari** [comment]
Emin değilim. Şunu dene bakalım:
https://stackoverflow.com/questions/28125886/where-to-put-static-files-for-spark-web-framework
