### ISSUE TITLE
[ILERI_JAVA_2018G] Javascript hakkında- Doğan koç

### ISSUE THREAD

**Issue by DoganNnN** [ozkansari/MyCourses#2]
hocam merhaba final projemizde derste öğrendiğimiz kürüphaneler harici kullanım yapmayın demişsiniz ama sormak istiyorum javascript bu uygulamada temel sayılacak seviyede acaba kullanabilirimiyim sorun olurmu

**Comment by ozkansari** [comment]
Javascript, css, bootstrap vb temel web özellikleri kullanılabilir. Ama tabi bunlar hakkında sunumda soru gelebilir size.

Spark yerine başka bir REST kütüphanesi, ya da DERBY yerine başka bir veritabanı, ya da GSON dışımda bir json kütüphanedi ve bunun gibi ekstra kütüphane kullanımı istemiyorum.

**Comment by DoganNnN** [comment]
tamam hocam sağolun anladım hocam birde şunu soracağım css sınıflarımı başka dosyalardan html im içinden <link href=".." ile ekleyemiyorum ancak html içinde <style> ile yazdığım css leri kullanabiliyorum 
acaba css dosyasını projenin neresine nasıl eklemek gerekiyorki benim yaptığım direk çalışmadı

**Comment by ozkansari** [comment]
Diğer yöntemleri de inceleyebilirsin: 
https://www.w3schools.com/css/css_howto.asp

#1  ile de ilgili olabilir
