### ISSUE TITLE
[YAZ_ORTAM_ARAC_2018G] Spring Boot

### ISSUE THREAD

**Issue by Kerimovic** [ozkansari/MyCourses#3]
![screenshot_2](https://user-images.githubusercontent.com/33569670/35471482-254697e8-036d-11e8-926f-66f51fe86843.png)

Resimdeki SpringBootOrnek.java'nın içerisindeki kodları farklı bir siteden mi çekiyorduk Proje Spring Boot'u tanımladım. Ancak bu sayfada hala hata ile karşılaşıyorum. Buradaki kodlar ile işlem yapıyorum bundan kaynaklı bir sorun mu?

**Comment by Kerimovic** [comment]
![screenshot_3](https://user-images.githubusercontent.com/33569670/35471564-7556c19e-036e-11e8-9166-6c31ec08d5ad.png)

Buradaki hata gibi.

**Comment by ozkansari** [comment]
"Buradaki hata gibi" diye belirttiğin ekran görüntüsünde ";" eksik. Ondan hata veriyor olabilir mi?

"kodları farklı siteden çekmek" diy bir şey yok. pom.xml tanımların doğruysa maven ilgili kütüphaneleri otomatik olarak indirir ve projenin başarılı derlenmesini sağlar.

**Comment by Kerimovic** [comment]
";" eksik fark ettim, ancak ekledikten sonra hatayı vermeye devam ediyor. Kodumda herhangi bir hata var mı bunu öğrenmek istiyorum sizlerden.

**Comment by ozkansari** [comment]
Kodun doğru görünüyor. pom.xml tanımın derste yaptığımız şekilde mi? Derste yaptığımız örnek zaten doğru ve çalışıyordu. Oradan bakıp ilerleyebilirsin.

**Comment by Kerimovic** [comment]
Teşekkürler hocam. Sorun çözüldü
