### ISSUE TITLE
Error when using @WebMvcTest annotation on a Spring Boot test class

### ISSUE THREAD

**Issue by valentine-ezugu** [ozkansari/MyCourses#4]
I've written a test class for a Spring MVC controller by following the "Testing the Spring MVC slice" section described here.  The class looks like this:  

 @RunWith(SpringRunner.class)
 @WebMvcTest(controllers=OurController.class) 
 public class OurControllerTest {  
   @Autowired     
    private MockMvc mvc;   

   @MockBean     
    private OurRepository ourRepository;   

    @Test   
     public void testGetStuff() {           } 

 

> MockHttpServletResponse:            Status = 401     Error message = null           Headers = {Cache-Control=[no-store], Pragma=[no-cache], WWW-Authenticate=[Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource"], Content-Type=[application/json;charset=UTF-8], X-Content-Type-Options=[nosniff], X-XSS-Protection=[1; mode=block], X-Frame-Options=[DENY]}      Content type = application/json;charset=UTF-8              Body = {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}     Forwarded URL = null    Redirected URL = null           Cookies = []  java.lang.AssertionError: Status  Expected :200 Actual   :401  <Click to see difference>       at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:54)     at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:81)     at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:664)     at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)     at com.ourcompany.mpt.api.repository.controllers.rest.our.OurControllerTest.testGetStuff(OurControllerTest.java:95)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)     at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75) [rest of stack trace removed]

The "Full authentication is required to access this resource" error is mentioned a link , and it suggests a couple workarounds. I tried changing the annotations on my test class to the following:
 
@WebMvcTest(controllers=OurController.class, includeFilters = @ComponentScan.Filter(classes=EnableWebSecurity.class)
 

Then I got the following error 

> 2016-12-19 15:43:59.218 ERROR 91076 [           main] c.o.m.u.c.error.ErrorHandlerController   : Access is denied  org.springframework.security.access.AccessDeniedException: Access is denied     at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) ~[spring-security-core-4.1.3.RELEASE.jar:4.1.3.RELEASE]     at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) ~[spring-security-core-4.1.3.RELEASE.jar:4.1.3.RELEASE]     at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65) ~[spring-security-core-4.1.3.RELEASE.jar:4.1.3.RELEASE]     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.3.RELEASE.jar:4.3.3.RELEASE]     at com.ourcompany.mpt.api.controllers.rest.our.OurController$$EnhancerBySpringCGLIB$$54993f0e.getStuff(<generated>) ~[classes/:na]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]     at org.springframework.web.servlet.mvc.method.anno
>

Then I tried the other workaround by changing the annotations on the test class to the following:
@RunWith(SpringRunner.class)
@WebMvcTest(controllers=OurController.class, secure=false)

Then I tried the other workaround by changing the annotations on the test class to the following:
@RunWith(SpringRunner.class)
@WebMvcTest(controllers=OurController.class, secure=false)

But still getting the same errors , my controllers mapping are accurate  every suggestion has been attempted 

Then I found another page that suggested using the @AutoConfigureMockMvc annotation to solve the "Full authentication is required to access this resource" error, so I changed the annotations to:

but same error 
example of controller

@Controller
@RequestMapping("/shoppingCart")
public class ShoppingCartController {

    @PreAuthorize("hasAuthority('USER')")
    @RequestMapping("/addItem")
    public String addItem(
            @ModelAttribute("book") Book book,
            @ModelAttribute("qty") String qty,
            Model model, Principal principal
    ) {
        User user = userService.findByUsername(principal.getName());

        try {
            book = bookService.findOne(book.getId());

            if (Integer.parseInt(qty) > book.getInStockNumber()) {
                model.addAttribute("notEnoughStock", true);
                return "forward:/bookDetail?id=" + book.getId();
            }

            CartItem cartItem = cartItemService.addBookToCartItem(book, user, Integer.parseInt(qty));
            model.addAttribute("addBookSuccess", true);

        } catch (NullPointerException e) {

        }

        return "forward:/bookDetail?id=" + book.getId();
    }

test

    @Test
    @WithMockUser(username = "V", authorities = {"USER"})
    public void addItemToShoppingCart() throws Exception {
        CartItem cartItem = new CartItem();
        String qty = "2";
        cartItem.setId(1L);
        Book book = new Book();
        User user = new User();
        book.setId(1L);
        book.getId();

        cartItem.setBook(book);
        when(userService.findByUsername(anyString())).thenReturn(user);

        when(bookService.findOne(anyLong())).thenReturn(book);

        when(cartItemService.addBookToCartItem(book, user, Integer.parseInt(qty))).thenReturn(cartItem);
        ObjectMapper mapper = new ObjectMapper();

        String bookAsString = mapper.writeValueAsString(book);
        mockMvc
                .perform(get("/shoppingCart/addItem")
                        .accept(MediaType.TEXT_HTML)
                        .contentType(MediaType.TEXT_HTML)
                        .param("book", bookAsString)
                        .param("qty", qty)).andExpect(status().isOk())
                .andReturn();
    }

**Comment by ozkansari** [comment]
https://stackoverflow.com/questions/41231731/error-when-using-webmvctest-annotation-on-a-spring-boot-test-class
