### ISSUE TITLE
[YAZ_ORTAM_ARAC_2018G] Rapor Hakkında

### ISSUE THREAD

**Issue by batuhank34** [ozkansari/MyCourses#5]
Hocam merhaba,
Proje raporlarımızı GitHub'a mı yükleyelim yoksa farklı bir şekilde mi ulaştıralım?

**Comment by ozkansari** [comment]
PDF olarak e-posta adresime göndermenizi hem de githuba yüklemenizi istiyorum. 

E-posta adresime gönderdiğiniz hali üzerinden not vereceğim ama github hesabınızda da bulunması iyi olur.
